import type { MediaItem } from "./types";

// Placeholder feed data so the UI is workable before the real API is wired
// up. Delete once lib/api.ts talks to the live backend.
export const MOCK_FEED: MediaItem[] = [
  {
    id: "1",
    mediaType: "photo",
    url: "https://picsum.photos/seed/photoop1/800/1000",
    thumbnailUrl: "https://picsum.photos/seed/photoop1/400/500",
    title: "Courtside",
    caption: "Courtside, second half.",
    tags: ["Arena", "Crowd", "Basketball"],
    categories: ["Sports"],
    uploader: { id: "u1", displayName: "jordan.k" },
    location: { label: "Chase Center, SF", lat: 37.768, lng: -122.3878 },
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    price: 25,
    likeCount: 14,
    saveCount: 3,
    viewCount: 210,
    copyrightText: "photo-op.ai/@jordan.k",
  },
  {
    id: "2",
    mediaType: "photo",
    url: "https://picsum.photos/seed/photoop2/800/1000",
    thumbnailUrl: "https://picsum.photos/seed/photoop2/400/500",
    title: "Encore",
    caption: "Encore.",
    tags: ["Concert", "Stage", "Lights"],
    categories: ["Music"],
    uploader: { id: "u2", displayName: "maya_p" },
    location: { label: "The Fillmore, SF", lat: 37.784, lng: -122.4332 },
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    price: 40,
    likeCount: 52,
    saveCount: 9,
    viewCount: 980,
    copyrightText: "photo-op.ai/@maya_p",
  },
  {
    id: "3",
    mediaType: "photo",
    url: "https://picsum.photos/seed/photoop3/800/1000",
    thumbnailUrl: "https://picsum.photos/seed/photoop3/400/500",
    title: "Finish Line",
    caption: "Finish line.",
    tags: ["Race", "Outdoors", "Crowd"],
    categories: ["Sports", "Outdoors"],
    uploader: { id: "u3", displayName: "devon.r" },
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    price: 0,
    likeCount: 3,
    saveCount: 0,
    viewCount: 40,
    copyrightText: "photo-op.ai/@devon.r",
  },
];
